version: 2

seeds:
  - name: employees
    description: A manual map of employees to customers
    columns:
      - name: employee_id
        description: Primary key
        tests:
          - unique
          - not_null
      